### ISSUE TITLE
use blank space for content

### ISSUE THREAD

**Issue by Stoabrogga** [azerothcore/wiki#103] opened 2019-08-05 07:47 UTC
Is it possible to use the blank space on the left side of the wiki for the actual content?
![wiki](https://user-images.githubusercontent.com/38475780/62447348-7a1fe000-b765-11e9-9d2c-be0c0e7b5547.jpg)

This would improve the readability of the wiki pages in my opinion.

**Comment by FrancescoBorzi** [comment] 2019-08-05 07:56
@Yehonal

**Comment by Yehonal** [comment] 2019-08-05 08:06
Yes of course we could, but we've decided to use the same css of github wiki that includes that space. Maybe we could reconsider it since our wiki is far more complex instead of wikis built with internal github system.

**Comment by BarbzYHOOL** [comment] 2019-08-05 15:36
> but we've decided to use the same css of github wiki that includes that space. 

What is the reason?

**Comment by Yehonal** [comment] 2019-08-05 16:09
@FrancescoBorzi's suggestion ^_^ as said before, if it's better we can change it of course.

However i think that github uses that space to avoid huge differences between a full-screen wiki and the responsive version.

**Comment by FrancescoBorzi** [comment] 2019-08-05 16:10
I think it's also because of readability patterns (this width looks like more readable than others, according to some study). However we can change it.

**Comment by BarbzYHOOL** [comment] 2019-08-06 00:03
with css it can be made super responsive, the problem is that it will prob need to rework the entire css (or do half hack shit) depending on how it's done first

**Comment by Stoabrogga** [comment] 2019-08-06 07:51
As it is now the wiki uses this CSS for small screens:
```css
.git-wiki-page{margin-top:60px}
```

And this for large screens:
```css
.git-wiki-page{padding-left:320px;padding-bottom:50px}
```

Can't we just override the second one and remove the left padding?

**Comment by FrancescoBorzi** [comment] 2019-08-06 08:04
Yes, we can. And, together with this change, I would also move the sidebar to the left to improve the readability

**Comment by Stoabrogga** [comment] 2019-08-06 08:06
Great idea :+1:

**Comment by Helias** [comment] 2019-08-06 13:27
Removing all the blank space will put the text on the left and for the readability is not worth, using the blank space for the sidebar is the right compromise to remove the blank space but mantain some space to "center" the text and improve the readability.
:+1:

**Comment by Yehonal** [comment] 2019-08-07 12:30
If you like i can change the theme in this way:

![image](https://user-images.githubusercontent.com/147092/62622935-e3e3e980-b91f-11e9-9f4c-e4535e251bf6.png)

**Comment by FrancescoBorzi** [comment] 2019-08-07 12:41
that is perfect

**Comment by Yehonal** [comment] 2019-08-07 12:57
Fixed in: 
https://github.com/azerothcore/wiki/commit/cb144f4ff77cceb7c621d067c8327e5dff32a36b

https://github.com/azerothcore/wiki/commit/860a2ec8765334612ea90109ffd5e99624e31bc7

**Closed by Yehonal** 2019-08-07 12:57 UTC

**Comment by Stoabrogga** [comment] 2019-08-07 14:24
looks great, thanks :+1:

**Comment by BarbzYHOOL** [comment] 2019-08-07 22:00
scss and bootstrap (probably), oof no idea how to use those

Plain pixel is certainly not the perfect solution in CSS but if it does the job for now
