### ISSUE TITLE
[Bug report]: Documentation is out of date and following it will corrupt your server

### ISSUE THREAD

**Issue by MrCeeJ** [azerothcore/wiki#868] opened 2023-02-05 17:19 UTC
### Describe the bug

Documentation is not up to date and will lead to loss of all your data.

if you follow the advice here:
https://www.azerothcore.org/wiki/update
and have a core newer than 3.0.0 but not current you CAN NOT follow the advice here: https://www.azerothcore.org/wiki/upgrade-from-pre-3.0.0-to-latest-master 
as it will break your database.

There are a number of breaking patches, apparantly you should use the discord annoucements channel and scroll back until you find the time you set up your server, and then scroll forwards updating to each breaking commit and rebuilding / restarting to adapt to them. There is no list of breaking changes or indication of this process on the wiki,

Anyone that doesn't do this will end up going past a breaking change and corrupting the data / schema and more or less be forced to ditch the server and start from scratch

### To reproduce

Build a server
let it go out of date
follow the documentation to update it
server is now corrupted and needs to be binned.

### Expected behavior

build a server
let it go out of date
follow the documentation to udpate it
server is now up to date.

### Desktop

Windows

### Smartphone

n/a

**Comment by heyitsbench** [comment] 2023-05-12 22:42
This is more or less a duplicate of #845.

**Closed** 2023-05-13 10:55 UTC
